# Generated by Django 3.2.2 on 2021-05-06 21:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogPosts',
            fields=[
                ('blogId', models.AutoField(primary_key=True, serialize=False)),
                ('blogName', models.CharField(max_length=255)),
                ('blogAuthor', models.CharField(max_length=100)),
                ('blogImageName', models.CharField(max_length=100)),
                ('blogUpdated', models.CharField(max_length=100)),
                ('dateOfPublish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('joinedDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
