# Generated by Django 3.2.2 on 2021-05-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposts',
            old_name='blogAuthor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='blogposts',
            old_name='blogImageName',
            new_name='ImageName',
        ),
        migrations.RenameField(
            model_name='blogposts',
            old_name='blogName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='blogposts',
            old_name='blogUpdated',
            new_name='Updated',
        ),
    ]
