# Generated by Django 3.2.2 on 2021-05-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210506_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='Content',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
