# Generated by Django 3.2.2 on 2021-06-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210608_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='is_superuser',
            new_name='admin',
        ),
        migrations.AddField(
            model_name='users',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
