# Generated by Django 3.2.2 on 2021-06-08 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210608_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='admin',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='staff',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
