# Generated by Django 3.2.2 on 2021-06-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210608_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='Content',
            field=models.TextField(),
        ),
    ]
