# Generated by Django 3.1.5 on 2021-11-16 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogposts_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('blogID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.blogposts')),
            ],
        ),
    ]
