# Generated by Django 3.1.5 on 2021-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blogcomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image1', models.CharField(max_length=100)),
                ('Image2', models.CharField(max_length=100)),
                ('Button1', models.CharField(max_length=20)),
                ('Button2', models.CharField(max_length=20)),
            ],
        ),
    ]
