# Generated by Django 3.1.5 on 2021-12-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_polls'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='Image1Votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='polls',
            name='Image2Votes',
            field=models.IntegerField(default=0),
        ),
    ]
