# Generated by Django 3.1.5 on 2021-12-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20211208_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='Category',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='polls',
            name='Category',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
