# Generated by Django 3.1.5 on 2021-12-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20211211_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='userEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
    ]
